### ISSUE TITLE
the crate `namigator` could not be found in registry index.

### ISSUE THREAD

**Issue by lifanflyfight** [gtker/namigator-rs#1]
While use command ```cargo add --features 'vanilla' namigator```, encounter an error:
error: the crate `namigator` could not be found in registry index.

**Comment by gtker** [comment]
Sorry for the late reply.

The problem was the I never actually published the crate to crates.io. I have now published it along with the version of `wow_world_base` that it depended on that also wasn't released.

`cargo add --features 'vanilla' namigator` will now work.
